[package]
description = "Modular, safe ELF loader for Polished OS, supporting UEFI and no_std environments."
edition = "2024"
license = "Zlib"
name = "polished_elf_loader"
readme = "./README.md"
repository = "https://codeberg.org/ofluffydev/polished"
version = "0.1.1"

[lib]
crate-type = ["rlib"]

[features]
uefi = ["dep:uefi"]

default = []

[dependencies]
log = { workspace = true }
polished_allocators = { path = "../allocators" }
polished_files = { version = "0.1.1", path = "../files", default-features = false }
polished_graphics = { version = "0.1.1", path = "../graphics", default-features = false }
uefi = { workspace = true, optional = true, features = [
  "alloc",
  "logger",
  "panic_handler",
] }
x86_64.workspace = true
xmas-elf = "0.10.0"
